### ISSUE TITLE
报错，FileNotFoundException build/hello.js

### ISSUE THREAD

**Issue by ithaibo** [xkli/WXSample#6]
在LocalActivity中加载本地JS报错了。日志如下：

04-14 19:51:52.173 19010-19010/com.weex.sample E/weex: java.io.FileNotFoundException: build/hello.js
                                                           at android.content.res.AssetManager.openAsset(Native Method)
                                                           at android.content.res.AssetManager.open(AssetManager.java:347)
                                                           at android.content.res.AssetManager.open(AssetManager.java:321)
                                                           at com.taobao.weex.utils.WXFileUtils.loadAsset(WXFileUtils.java:231)
                                                           at com.weex.sample.LocalActivity.onCreate(LocalActivity.java:34)
                                                           at android.app.Activity.performCreate(Activity.java:6679)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ithaibo** [comment]
知道了， “build/hello.js”， build是assets下的一个文件夹，hello.js是hello.we编译后的用于app的js文件。
